### ISSUE TITLE
Netbeans 8.1 : Warning: You have to connect to the Internet

### ISSUE THREAD

**Issue by mlang38** [junichi11/netbeans-gitignore-io-plugin#3]
I don't have inspected more than that for now, but when you click on the "Generate gitignore file" button in netbeans 8.1, it shows a popup with the aforementioned message.

**Comment by junichi11** [comment]
@mlang38 Thanks for reporting it.

I've added a logger. So, could you please try using the development version? Just confirm IDE log messages when a popup is shown.
https://github.com/junichi11/netbeans-gitignore-io-plugin/releases/tag/v0.2.0 (0.2.0.1-dev)

**Comment by mlang38** [comment]
I've uninstalled the 0.2.0 public plugin and installed by hand the 0.2.0.1-dev.nbm from your release page. I've launched Netbeans 8.1 from a terminal and clicked on the "Generate gitignore file" button, and I've had the following Exception :

```java
java.lang.NullPointerException
	at com.junichi11.netbeans.gitignoreio.ui.GitignoreListPanel.getAvailableGitignoresText(GitignoreListPanel.java:243)
	at com.junichi11.netbeans.gitignoreio.ui.GitignoreListPanel.getAvailableGitignores(GitignoreListPanel.java:222)
	at com.junichi11.netbeans.gitignoreio.ui.GitignoreListPanel.addGitignores(GitignoreListPanel.java:144)
	at com.junichi11.netbeans.gitignoreio.ui.GitignoreListPanel.init(GitignoreListPanel.java:107)
	at com.junichi11.netbeans.gitignoreio.ui.GitignoreListPanel.<init>(GitignoreListPanel.java:93)
	at com.junichi11.netbeans.gitignoreio.ui.GitignoreListPanel.<clinit>(GitignoreListPanel.java:83)
Caused: java.lang.ExceptionInInitializerError
	at com.junichi11.netbeans.gitignoreio.ui.actions.GenerateGitIgnoreAction$1.run(GenerateGitIgnoreAction.java:108)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
[catch] at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

PS: I use Netbeans for PHP dev and so I don't have the full Netbeans Java version. I'm not used to Java dev and Netbeans plugin dev, so sorry if I'm not of very good help. :wink:

**Comment by mlang38** [comment]
I get the same Exception from a new blank PHP project without already existing .gitignore file.

**Comment by junichi11** [comment]
Oh, sorry, I've created a new dev version. 
https://github.com/junichi11/netbeans-gitignore-io-plugin/releases/tag/v0.2.0 (0.2.0.2-dev)

You can install it without uninstalling the old version ;) 
You can look at a log from Menu : View > IDE log

**Comment by mlang38** [comment]
```java
WARNING [org.openide.filesystems.Ordering]: Found same position 2 550 for both Projects/Actions/com-junichi11-netbeans-gitignoreio-ui-actions-GenerateGitIgnoreAction.shadow and Projects/Actions/org-netbeans-modules-vagrant-ui-actions-VagrantAction.shadow
WARNING [com.junichi11.netbeans.gitignoreio.ui.GitignoreListPanel]: Received fatal alert: handshake_failure
```

**Comment by mlang38** [comment]
When I installed 8.1 I imported my previous preferences from 8.0.2 . So I checked if ".netbeans/8.1/config/Preferences/com/junichi11/netbeans/gitignoreio.properties", but nothing really fancy in it. I thought it could have a bad URL for gitignore.io or something like that, but no :disappointed:

**Comment by junichi11** [comment]
Thanks for your confirmation and providing a log. Umm, does it work fine in 8.0.2?

**Comment by junichi11** [comment]
Could you write your IDE information?

Help > About 
e.g. 
Product Version: NetBeans IDE 8.1 (Build 201510222201)
Java: 1.7.0_80; Java HotSpot(TM) 64-Bit Server VM 24.80-b11
Runtime: Java(TM) SE Runtime Environment 1.7.0_80-b15
System: Linux version 3.13.0-68-generic running on amd64; UTF-8

**Comment by mlang38** [comment]
Product Version: NetBeans IDE 8.1 (Build 201510222201)
Java: 1.8.0_60; Java HotSpot(TM) 64-Bit Server VM 25.60-b23
Runtime: Java(TM) SE Runtime Environment 1.8.0_60-b27
System: Linux version 3.13.0-68-generic running on amd64; UTF-8; fr_FR (nb)
User directory: /home/mlangevin/.netbeans/8.1
Cache directory: /home/mlangevin/.cache/netbeans/8.1

Ubuntu 14.04 64 bits up to date

**Comment by mlang38** [comment]
It worked fine on Netbeans 8.0.2 but I guess it was the 0.1.4 version of your plugin, I cant remember. I've uninstalled the 8.0.2 Netbeans, but do you want me to test 0.2.0.2 on it ?

**Comment by junichi11** [comment]
> It worked fine on Netbeans 8.0.2

Umm, I just fixed some dependencies... So, I'll try building the plugin with version 0.1.4.

> do you want me to test 0.2.0.2 on it

No, 0.2.x does not work in NetBean 8.0.2.

Thanks.

**Comment by junichi11** [comment]
I've created version 0.1.4.1 for nb81. Could you try testing it? 
https://github.com/junichi11/netbeans-gitignore-io-plugin/releases/tag/v0.1.4 (0.1.4.1-dev)

Another idea... just try using Java 7. But I cannot reproduce it both Java 7 and 8.

**Comment by mlang38** [comment]
Doesn't work better with 0.1.4.1-dev . It seems that the JRE used by Netbeans is the one bundled with it, cause my system JRE is 1.7, not 1.8.

**Comment by xyfantis** [comment]
I have exactly the same problem

Here is my setup
Product Version: NetBeans IDE 8.1 (Build 201510222201)
Java: 1.8.0_60; Java HotSpot(TM) 64-Bit Server VM 25.60-b23
Runtime: Java(TM) SE Runtime Environment 1.8.0_60-b27
System: Windows 10 version 10.0 running on amd64; Cp1253; en_US (nb)

**Comment by junichi11** [comment]
I changed a bit. 
https://github.com/junichi11/netbeans-gitignore-io-plugin/releases/tag/v0.2.0 (0.2.0.3-dev)

Could you try to use it if possible?

Thanks.

**Comment by mlang38** [comment]
Nothing changes for me, still the warning

**Comment by junichi11** [comment]
@mlang38 Thanks for testing it. Umm, I'm not sure the cause yet, sorry.

**Comment by vanquang9387** [comment]
I have same exceptions. Here are my setup:
Product Version: NetBeans IDE 8.1 (Build 201510222201)
Updates: NetBeans IDE is updated to version NetBeans 8.1 Patch 1
Java: 1.8.0_60; Java HotSpot(TM) 64-Bit Server VM 25.60-b23
Runtime: Java(TM) SE Runtime Environment 1.8.0_60-b27
System: Windows 10 version 10.0 running on amd64; Cp1252; en_US (nb)
